INSERT INTO articles(title,text) VALUES('title 1','text 1');
INSERT INTO articles(title,text) VALUES('title 2','text 2');
INSERT INTO articles(title,text) VALUES('title 3','text 3');
INSERT INTO articles(title,text) VALUES('title 4','text 4');
INSERT INTO articles(title,text) VALUES('title 5','text 5');
INSERT INTO articles(title,text) VALUES('title 6','text 6');
INSERT INTO articles(title,text) VALUES('title 7','text 7');
INSERT INTO articles(title,text) VALUES('title 8','text 8');
INSERT INTO articles(title,text) VALUES('title 9','text 9');
INSERT INTO articles(title,text) VALUES('title 10','text 10');
INSERT INTO articles(title,text) VALUES('title 11','text 11');
INSERT INTO articles(title,text) VALUES('title 12','text 12');
INSERT INTO articles(title,text) VALUES('title 13','text 13');
INSERT INTO articles(title,text) VALUES('title 14','text 14');
INSERT INTO articles(title,text) VALUES('title 15','text 15');
INSERT INTO articles(title,text) VALUES('title 16','text 16');
INSERT INTO articles(title,text) VALUES('title 17','text 17');
INSERT INTO articles(title,text) VALUES('title 18','text 18');
INSERT INTO articles(title,text) VALUES('title 19','text 19');
INSERT INTO articles(title,text) VALUES('title 20','text 20');
INSERT INTO articles(title,text) VALUES('title 21','text 21');
INSERT INTO articles(title,text) VALUES('title 22','text 22');
INSERT INTO articles(title,text) VALUES('title 23','text 23');
INSERT INTO articles(title,text) VALUES('title 24','text 24');
INSERT INTO articles(title,text) VALUES('title 25','text 25');
INSERT INTO articles(title,text) VALUES('title 26','text 26');
INSERT INTO articles(title,text) VALUES('title 27','text 27');
INSERT INTO articles(title,text) VALUES('title 28','text 28');
INSERT INTO articles(title,text) VALUES('title 29','text 29');
INSERT INTO articles(title,text) VALUES('title 30','text 30');
INSERT INTO articles(title,text) VALUES('title 31','text 31');
INSERT INTO articles(title,text) VALUES('title 32','text 32');
INSERT INTO articles(title,text) VALUES('title 33','text 33');
INSERT INTO articles(title,text) VALUES('title 34','text 34');
INSERT INTO articles(title,text) VALUES('title 35','text 35');
INSERT INTO articles(title,text) VALUES('title 36','text 36');
INSERT INTO articles(title,text) VALUES('title 37','text 37');
INSERT INTO articles(title,text) VALUES('title 38','text 38');
INSERT INTO articles(title,text) VALUES('title 39','text 39');
INSERT INTO articles(title,text) VALUES('title 40','text 40');
INSERT INTO articles(title,text) VALUES('title 41','text 41');
INSERT INTO articles(title,text) VALUES('title 42','text 42');
INSERT INTO articles(title,text) VALUES('title 43','text 43');
INSERT INTO articles(title,text) VALUES('title 44','text 44');
INSERT INTO articles(title,text) VALUES('title 45','text 45');
INSERT INTO articles(title,text) VALUES('title 46','text 46');
INSERT INTO articles(title,text) VALUES('title 47','text 47');
INSERT INTO articles(title,text) VALUES('title 48','text 48');
INSERT INTO articles(title,text) VALUES('title 49','text 49');
INSERT INTO articles(title,text) VALUES('title 50','text 50');
INSERT INTO articles(title,text) VALUES('title 51','text 51');
INSERT INTO articles(title,text) VALUES('title 52','text 52');
INSERT INTO articles(title,text) VALUES('title 53','text 53');
INSERT INTO articles(title,text) VALUES('title 54','text 54');
INSERT INTO articles(title,text) VALUES('title 55','text 55');
INSERT INTO articles(title,text) VALUES('title 56','text 56');
INSERT INTO articles(title,text) VALUES('title 57','text 57');
INSERT INTO articles(title,text) VALUES('title 58','text 58');
INSERT INTO articles(title,text) VALUES('title 59','text 59');
INSERT INTO articles(title,text) VALUES('title 60','text 60');
INSERT INTO articles(title,text) VALUES('title 61','text 61');
INSERT INTO articles(title,text) VALUES('title 62','text 62');
INSERT INTO articles(title,text) VALUES('title 63','text 63');
INSERT INTO articles(title,text) VALUES('title 64','text 64');
INSERT INTO articles(title,text) VALUES('title 65','text 65');
INSERT INTO articles(title,text) VALUES('title 66','text 66');
INSERT INTO articles(title,text) VALUES('title 67','text 67');
INSERT INTO articles(title,text) VALUES('title 68','text 68');
INSERT INTO articles(title,text) VALUES('title 69','text 69');
INSERT INTO articles(title,text) VALUES('title 70','text 70');
INSERT INTO articles(title,text) VALUES('title 71','text 71');
INSERT INTO articles(title,text) VALUES('title 72','text 72');
INSERT INTO articles(title,text) VALUES('title 73','text 73');
INSERT INTO articles(title,text) VALUES('title 74','text 74');
INSERT INTO articles(title,text) VALUES('title 75','text 75');
INSERT INTO articles(title,text) VALUES('title 76','text 76');
INSERT INTO articles(title,text) VALUES('title 77','text 77');
INSERT INTO articles(title,text) VALUES('title 78','text 78');
INSERT INTO articles(title,text) VALUES('title 79','text 79');
INSERT INTO articles(title,text) VALUES('title 80','text 80');
INSERT INTO articles(title,text) VALUES('title 81','text 81');
INSERT INTO articles(title,text) VALUES('title 82','text 82');
INSERT INTO articles(title,text) VALUES('title 83','text 83');
INSERT INTO articles(title,text) VALUES('title 84','text 84');
INSERT INTO articles(title,text) VALUES('title 85','text 85');
INSERT INTO articles(title,text) VALUES('title 86','text 86');
INSERT INTO articles(title,text) VALUES('title 87','text 87');
INSERT INTO articles(title,text) VALUES('title 88','text 88');
INSERT INTO articles(title,text) VALUES('title 89','text 89');
INSERT INTO articles(title,text) VALUES('title 90','text 90');
INSERT INTO articles(title,text) VALUES('title 91','text 91');
INSERT INTO articles(title,text) VALUES('title 92','text 92');
INSERT INTO articles(title,text) VALUES('title 93','text 93');
INSERT INTO articles(title,text) VALUES('title 94','text 94');
INSERT INTO articles(title,text) VALUES('title 95','text 95');
INSERT INTO articles(title,text) VALUES('title 96','text 96');
INSERT INTO articles(title,text) VALUES('title 97','text 97');
INSERT INTO articles(title,text) VALUES('title 98','text 98');
INSERT INTO articles(title,text) VALUES('title 99','text 99');
INSERT INTO articles(title,text) VALUES('title 100','text 100');

INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 2',9,2);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 2',43,2);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 2',0,2);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 2',15,2);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 2',38,2);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 2',91,2);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 2',21,2);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 3',18,3);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 3',59,3);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 3',29,3);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 3',59,3);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 4',17,4);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 4',88,4);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 4',33,4);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 4',19,4);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 4',97,4);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 4',45,4);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 4',44,4);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=8) text for 4',59,4);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 5',33,5);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 5',52,5);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 5',38,5);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 5',71,5);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 6',85,6);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 6',55,6);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 6',11,6);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 7',11,7);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 7',67,7);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 7',69,7);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 7',3,7);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 7',7,7);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 7',98,7);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 8',11,8);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 9',88,9);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 10',26,10);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 11',1,11);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 11',6,11);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 11',48,11);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 11',47,11);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 11',15,11);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 11',20,11);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 11',63,11);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 12',15,12);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 13',10,13);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 15',38,15);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 15',28,15);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 15',17,15);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 15',18,15);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 15',82,15);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 16',73,16);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 16',73,16);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 16',28,16);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 18',43,18);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 18',60,18);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 18',59,18);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 18',45,18);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 18',21,18);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 18',74,18);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 18',46,18);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 19',52,19);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 19',56,19);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 19',71,19);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 20',52,20);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 21',11,21);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 22',36,22);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 22',34,22);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 23',15,23);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 24',81,24);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 24',94,24);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 24',60,24);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 24',82,24);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 24',52,24);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 24',45,24);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 24',59,24);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=8) text for 24',42,24);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 25',58,25);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 25',15,25);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 26',62,26);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 26',34,26);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 26',23,26);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 26',78,26);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 26',29,26);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 26',81,26);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 26',3,26);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=8) text for 26',26,26);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=9) text for 26',83,26);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 27',24,27);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 27',5,27);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 27',73,27);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 27',89,27);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 27',39,27);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 27',44,27);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 28',22,28);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 28',37,28);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 28',50,28);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 28',30,28);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 28',1,28);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 28',48,28);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 28',64,28);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=8) text for 28',26,28);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=9) text for 28',79,28);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 29',88,29);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 30',18,30);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 30',67,30);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 30',23,30);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 30',1,30);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 30',83,30);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 30',37,30);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 30',76,30);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 31',40,31);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 31',24,31);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 31',32,31);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 31',71,31);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 31',63,31);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 31',98,31);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 31',62,31);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=8) text for 31',46,31);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=9) text for 31',69,31);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 32',5,32);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 33',53,33);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 33',73,33);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 34',21,34);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 35',3,35);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 36',76,36);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 36',82,36);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 36',39,36);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 36',39,36);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 36',72,36);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 36',39,36);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 37',92,37);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 37',15,37);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 37',93,37);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 37',23,37);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 37',54,37);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 39',31,39);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 39',82,39);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 39',21,39);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 39',10,39);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 39',52,39);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 39',21,39);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 39',48,39);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 40',51,40);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 40',24,40);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 40',81,40);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 40',93,40);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 40',6,40);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 40',64,40);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 42',51,42);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 42',76,42);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 42',5,42);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 42',32,42);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 43',98,43);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 43',3,43);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 43',83,43);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 43',7,43);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 44',10,44);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 44',39,44);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 44',17,44);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 44',64,44);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 44',88,44);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 45',3,45);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 45',3,45);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 45',57,45);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 45',4,45);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 45',6,45);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 45',67,45);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 45',75,45);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 46',43,46);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 46',72,46);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 46',61,46);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 46',32,46);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 46',80,46);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 46',60,46);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 46',91,46);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 47',88,47);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 47',11,47);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 47',32,47);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 47',96,47);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 47',78,47);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 47',40,47);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 47',0,47);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=8) text for 47',26,47);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 48',69,48);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 48',98,48);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 48',68,48);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 48',87,48);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 49',24,49);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 49',84,49);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 49',3,49);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 49',19,49);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 51',23,51);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 51',58,51);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 51',40,51);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 51',55,51);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 51',3,51);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 52',32,52);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 52',81,52);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 52',40,52);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 52',58,52);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 53',74,53);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 53',45,53);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 53',99,53);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 53',12,53);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 54',16,54);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 54',89,54);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 54',66,54);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 54',43,54);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 54',26,54);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 54',57,54);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 54',80,54);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=8) text for 54',61,54);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=9) text for 54',77,54);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 55',32,55);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 55',70,55);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 55',60,55);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 56',16,56);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 57',59,57);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 57',65,57);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 57',69,57);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 57',76,57);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 57',4,57);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 58',90,58);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 59',82,59);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 59',10,59);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 59',78,59);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 59',39,59);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 59',22,59);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 59',37,59);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 59',68,59);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 60',34,60);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 60',96,60);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 60',78,60);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 60',56,60);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 60',16,60);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 60',67,60);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 60',89,60);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=8) text for 60',32,60);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=9) text for 60',40,60);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 61',17,61);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 61',56,61);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 61',41,61);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 61',33,61);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 61',68,61);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 61',60,61);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 61',62,61);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 62',60,62);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 62',44,62);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 62',2,62);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 62',9,62);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 62',64,62);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 63',3,63);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 63',56,63);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 63',36,63);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 63',86,63);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 63',52,63);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 64',74,64);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 64',80,64);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 64',10,64);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 64',60,64);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 64',84,64);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 64',86,64);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 64',27,64);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 65',80,65);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 65',68,65);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 65',26,65);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 65',71,65);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 65',92,65);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 66',77,66);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 66',24,66);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 66',22,66);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 67',73,67);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 67',41,67);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 67',52,67);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 67',33,67);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 67',51,67);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 67',91,67);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 67',35,67);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=8) text for 67',91,67);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 68',0,68);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 69',37,69);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 69',53,69);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 69',45,69);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 69',32,69);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 69',22,69);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 70',16,70);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 70',58,70);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 70',98,70);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 70',42,70);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 70',94,70);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 70',86,70);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 72',31,72);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 72',82,72);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 72',50,72);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 72',11,72);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 72',44,72);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 73',19,73);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 73',86,73);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 73',49,73);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 73',5,73);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 73',32,73);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 75',51,75);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 75',81,75);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 75',57,75);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 75',67,75);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 76',16,76);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 76',66,76);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 76',0,76);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 76',50,76);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 76',90,76);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 76',65,76);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 76',97,76);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=8) text for 76',47,76);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 79',48,79);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 79',28,79);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 79',51,79);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 79',80,79);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 79',50,79);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 80',45,80);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 80',93,80);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 80',33,80);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 81',21,81);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 81',91,81);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 81',74,81);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 81',51,81);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 81',32,81);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 81',15,81);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 82',66,82);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 82',27,82);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 82',33,82);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 82',50,82);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 82',72,82);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 82',97,82);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 82',80,82);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=8) text for 82',38,82);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 83',34,83);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 84',39,84);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 84',47,84);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 84',1,84);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 84',28,84);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 84',27,84);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 84',41,84);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 85',89,85);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 85',13,85);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 85',81,85);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 85',66,85);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 85',35,85);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 85',2,85);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 85',41,85);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 88',57,88);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 88',1,88);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 88',72,88);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 89',99,89);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 89',18,89);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 89',22,89);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 89',41,89);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 89',27,89);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 89',2,89);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 89',89,89);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=8) text for 89',23,89);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=9) text for 89',63,89);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 90',26,90);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 90',74,90);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 90',38,90);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 90',63,90);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 90',33,90);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 91',85,91);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 91',34,91);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 91',27,91);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 91',52,91);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 91',51,91);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 92',66,92);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 92',49,92);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 92',24,92);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 92',72,92);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 92',13,92);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 93',21,93);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 93',55,93);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 93',81,93);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 93',69,93);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 94',89,94);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 95',1,95);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 95',85,95);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 95',0,95);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 95',42,95);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 95',88,95);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 95',68,95);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 95',44,95);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 96',54,96);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 96',13,96);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 96',68,96);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 97',20,97);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 97',35,97);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 97',53,97);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 97',40,97);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 97',82,97);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=6) text for 97',21,97);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=7) text for 97',27,97);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 98',7,98);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 98',46,98);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 98',51,98);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 98',56,98);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 98',43,98);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=1) text for 99',77,99);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=2) text for 99',83,99);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=3) text for 99',11,99);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=4) text for 99',21,99);
INSERT INTO comments(text,score,article_id) VALUES('comment (id=5) text for 99',27,99);
